POST http://localhost:3201/api/post/inventory/add HTTP/1.1
Content-Type: application/json

{
  "OwnerEmailForBody": "YOUR_EMAIL",
    "User_idForBody": "YOUR_USER_ID",
    "ProductName": "PRODUCT_NAME",
    "ProductCategory": "PRODUCT_CATEGORY",
    "ProductSKU": "PRODUCT_SKU",
    "ProductQuantity": "PRODUCT_QUANTITY",
    "ProductPrice": "PRODUCT_PRICE",
    "ProductExpiryDate": "PRODUCT_EXPIRY_DATE (OPTIONAL)",
    "ProductManufacturingDate": "PRODUCT_MANUFACTURING_DATE (OPTIONAL)",
    "ProductDescription": "PRODUCT_DESCRIPTION",
}