POST http://localhost:3201/api/post/auth/CreateAccount HTTP/1.1
Content-Type: application/json

{
  "Name":"YOUR NAME",
  "Email":"YOUR EMAIL",
  "Password":"YOUR PASSWORD",
  "Phone":0000000000,
  "Address":"YOUR ADDRESS",
  "City":"YOUR CITY",
  "State":"YOUR STATE",
  "Zip":000000,
  "Country":"YOUR COUNTRY",
  "isTermsAccepted":true,
  "ShopName":"YOUR SHOP NAME",
  "ShopAddress": "YOUR SHOP ADDRESS",
  "SecurityQuestion":"YOUR SECURITY QUESTION",
  "SecurityAnswer":"YOUR SECURITY ANSWER",
  "isGSTIN":true,
  "GSTIN":"YOUR GSTIN",
  "PAN":"YOUR PAN",
  }