PUT http://localhost:3201/api/put/order/update-order-details HTTP/1.1
Content-Type: application/json

{
    "OwnerEmailForBody":"YOUR_EMAIL",
    "User_idForBody": "YOUR_USER_ID",
    "OrderID": "ORDER_ID",
    "DeliveryAddress":"DELIVERY_ADDRESS",
    "DeliveryDate": "DELIVERY_DATE",
    "DeliveryStatus": "DELIVERY_STATUS",
    "PaymentMethod": "PAYMENT_METHOD",
    "PaymentStatus": "PAYMENT_STATUS",
}