POST http://localhost:3201/post/auth/CreateAccount HTTP/1.1
Content-Type: application/json

{
  "Name":"Ankan Saha",
  "Email":"ankansahaofficial@gmail.com",
  "Password":"Ankan@157",
  "Phone":7063355213,
  "Address":"Near Daluabari Bazar",
  "City":"Ranaghat",
  "State":"West Bengal",
  "Zip":741504,
  "Country":"India",
  "isTermsAccepted":true,
  "ShopName":"Saha Medical",
  "ShopAddress": "Near Daluabari Bazar",
  "SecurityQuestion":"What is your oet name ?",
  "SecurityAnswer":"Chiku",
  "isGSTIN":true,
  "GSTIN":"GGH55844GHHIN",
  "PAN":"OVFPS3949G"
  }