POST http://localhost:3201/api/post/forgot-password/reset-password HTTP/1.1
Content-Type: application/json

{
    "User_idForBody":70292480,
    "OwnerEmailForBody":"ankansahaofficial@gmail.com",
    "Token":"eyJhbGciOiJIUzI1NiJ9.eyJfaWQiOiI2NDkxYzNlNmI5MmY4NmUyZDQzMmI1YTciLCJVc2VyX2lkIjo3MDI5MjQ4MCwiTmFtZSI6IkFua2FuIFNhaGEiLCJFbWFpbCI6ImFua2Fuc2FoYW9mZmljaWFsQGdtYWlsLmNvbSIsIlBhc3N3b3JkIjoiRW5jcnlwdGVkIHdpdGggQ3J5cHRvIiwiUGhvbmUiOjcwNjMzNTUyMTMsIkFkZHJlc3MiOiJOZWFyIERhbHVhYmFyaSBCYXphciIsIkNpdHkiOiJSYW5hZ2hhdCIsIlN0YXRlIjoiV2VzdCBCZW5nYWwiLCJaaXAiOjc0MTUwNCwiQ291bnRyeSI6IkluZGlhIiwiU2VjdXJpdHlRdWVzdGlvbiI6IldoYXQgaXMgeW91ciBvZXQgbmFtZSA_IiwiU2VjdXJpdHlBbnN3ZXIiOiJjaGlrdSIsIlN0YXR1cyI6IkFjdGl2ZSIsImlzVGVybXNBY2NlcHRlZCI6dHJ1ZSwiU2hvcE5hbWUiOiJTYWhhIE1lZGljYWwiLCJTaG9wQWRkcmVzcyI6Ik5lYXIgRGFsdWFiYXJpIEJhemFyIiwiaXNHU1RJTiI6InRydWUiLCJHU1RJTiI6IkdHSDU1ODQ0R0hISU4iLCJQQU4iOiJPVkZQUzM5NDlHIiwiQ3JlYXRlZEF0IjoiMjAyMy0wNi0yMFQxNToyMToxMC43NjFaIiwiX192IjowfQ.7VMB7r232D7PdRcPVe7WeVgbNH_l7EBJAt5nhMMaltk",
    "NewPassword":"Ankan@1578"
}