POST http://localhost:3201/api/post/forgot-password/reset-password HTTP/1.1
Content-Type: application/json

{
    "User_idForBody":70292480,
    "OwnerEmailForBody":"ankansahaofficial@gmail.com",
    "Token":"YOUR_JWT_TOKEN",
    "NewPassword":"Ankan@1578"
}
