POST http://localhost:3201/api/post/employee/create HTTP/1.1
Content-Type: application/json

{
  "User_idForBody": "YOUR_USER_ID",
  "OwnerEmailForBody":"YOUR_EMAIL",
  "EmployeeName":"EMPLOYEE_NAME",
  "EmployeeMonthlySalary":"EMPLOYEE_MONTHLY_SALARY",
  "EmployeeEmail":"EMPLOYEE_EMAIL",
  "EmployeePhoneNumber":"7063355213",
  "EmployeeDateOfJoining":"EMPLOYEE_DATE_OF_JOINING",
  "EmployeeRole":"EMPLOYEE_ROLE",
}