POST http://localhost:3201/api/post/employee/create HTTP/1.1
Content-Type: application/json

{
  "User_idForBody": 842,
  "OwnerEmailForBody":"ankansahaofficial@gmail.com",
  "EmployeeName":"Ankan Saha",
  "EmployeeMonthlySalary":"10000",
  "EmployeeEmail":"ankansahaofficial@gmail.com",
  "EmployeePhoneNumber":"7063355213",
  "EmployeeDateOfJoining":"2023-04-25",
  "EmployeeRole":"Owner"
}