PUT http://localhost:3201/api/put/category/update-category HTTP/1.1
Content-Type: application/json

{
    "User_idForBody":"YOUR_USER_ID",
    "OwnerEmailForBody": "YOUR_EMAIL",
    "CategoryID": "YOUR_CATEGORY_ID",
    "CategoryName": "Test Categors",
    "CategoryDescription": "Test Category Description"
}
