PUT http://localhost:3201/api/put/category/update-category HTTP/1.1
Content-Type: application/json

{
    "User_idForBody":842,
    "OwnerEmailForBody": "ankansahaofficial@gmail.com",
    "CategoryID": 4496481567,
    "CategoryName": "Test Categorss",
    "CategoryDescription": "Test Category Description"
}
